steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/pixels:latest', '.']
  - name: 'us.gcr.io/$PROJECT_ID/pixels:latest'
    dir: '/app'
    args: ['yarn', 'ci:config']
    env:
      - 'SERVICE_ACCOUNT_BASE64=$_SERVICE_ACCOUNT_BASE64'
      - 'GOOGLE_APPLICATION_CREDENTIALS=$_GOOGLE_APPLICATION_CREDENTIALS'
      - 'IMGUR_CLIENT_ID=$_IMGUR_CLIENT_SECRET'
      - 'IMGUR_CLIENT_SECRET=$_IMGUR_CLIENT_ID'
  - name: 'us.gcr.io/$PROJECT_ID/pixels:latest'
    dir: '/app'
    args: ['yarn', 'ci:deploy']
    env:
      - 'FIREBASE_TOKEN=$_FIREBASE_TOKEN'
      - 'FIREBASE_PROJECT=$_FIREBASE_PROJECT'
images: ['us.gcr.io/$PROJECT_ID/pixels:latest']
timeout: 3600s
